# Generated by Django 6.0.5 on 2026-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate_education_experience_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=50),
        ),
    ]
