# Generated by Django 6.0.5 on 2026-05-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certificate_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text="Example: ['Python', 'Pandas', 'NumPy']"),
        ),
    ]
