# Generated by Django 6.0.5 on 2026-05-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, help_text='Example: Python, Pandas, NumPy', null=True),
        ),
    ]
