# Generated by Django 6.0.5 on 2026-05-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_project_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('data analysis', 'Data Analysis'), ('predictive modeling', 'Predictive Modeling'), ('machine learning', 'Machine Learning'), ('deep learning', 'Deep Learning'), ('computer vision', 'Computer Vision'), ('clustering', 'Clustering / Unsupervised Learning'), ('web development', 'Web Development'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
    ]
